### ISSUE TITLE
Failed to create package: Cannot modify packages for remote host "entropic.dev"

### ISSUE THREAD

**Issue by gr2m** [entropic-dev/entropic#124]
I know it’s early days and probably I’ve missed something obvious. I’ll also try to understand the reason myself and update the issue as I do. But I thought others might run into the same problem so why not create it for everyone to track.

Here is what I did

- [x] successfully installed the CLI
- [x] successfully logged in using my GitHub account `@gr2m`
- [x] created a new folder with a `Package.toml` and an `index.js`

  ```toml
  [registries."https://entropic.dev"]
  token = "ent_v1_6afb7369-8d64-43a5-bc95-841eba208500"
  ```

  ```js
  module.exports = () => {
    console.log('It me, @gr2m!')
  }
  ```
- [ ] I get an error when running `ds publish` in the same folder

  ```shel
  $ ds publish
  ERR! Failed to create package: 
  ERR! Cannot modify packages for remote host "entropic.dev" 
  ```

Any pointers much appreciated

**Comment by toddself** [comment]
What does your Package.toml look like?

**Comment by gr2m** [comment]
Oppsie doopies, I passed the wrong content in my issue description, fixed it now.

The content is

```toml
name = "gr2m@entropic.dev/gr2m"
version = "1.0.0"
```
