### ISSUE TITLE
Run Scripts: Do we need them?

### ISSUE THREAD

**Issue by junoatscroll** [entropic-dev/entropic#150]
Main idea
===
Supporting arbitrary task running could overcomplicate the `ds` cli. Instead, support a limited set of hooks specifically related to package management, a la git hooks, and leave task running to other tools.

Motivation
===
Motivated by #85,  some tweets, and a comment by Ceej in https://github.com/entropic-dev/entropic/pull/135#discussion_r290351447 , and some thoughts about decision-by-default from Ceej's JSConfEU talk... does `ds` need to support arbitrary run commands? Or is this territory better covered by tools like gulp, yeoman, make, and whatever else javascript developers come up with down the line?

It occurs to me that having hooks for various point in the package lifecycle are very useful, such as pre-publish, post-install, etc. One approach could be to handle it like git, with a well-known path to an executable script file. Cross-platform compatibility is an issue, and Windows support is important for a tool that wants to appeal to the broad masses of developers of all backgrounds. It would be important to support pointing to a *nix executable script as well as a .bat file.

Not in issue scope 
===
- I think the approach to package binstubs is a separate (but sort of related) conversation.
- Git has server-side hooks, which I think could be a really interesting exploration here, especially as entropic makes it much more likely that someone (or some team) might be running their own registry and want to tweak it to their development workflow. But let's set that aside for right now and focus on the cli in this issue.

Possible sketch
===
- Don't support arbitrary additional run script commands in the `ds` cli
- Define lifecycle hooks for package installation and publishing. Say, `install`, `publish`
- During installation (or pubilsh), trigger to `pre-install` and `post-install` events. Try to handle the events by resolving them to files. To resolve, look for files in a directory (e.g. `ds/hooks/<file>`). On *nix, look for e.g. `pre-install`. On Windows, look for `pre-install.bat`. If the files exist and are executable, run them. (Maybe with some standard ENV variables, not defined in this sketch, but feel free to discuss). If they exit with a non-zero error code, abort the next step. If they exit normally, continue.
- Potential candidates for other hook-able events should be related to critical package workflow, potentially things like `upgrade` or `audit`. Other commands related to general development, but not package management, would be left up to the developer's other preferred tooling.

Alternately, other than a well-known path, the hook scripts could be configurable in Package.toml

Thanks in advance for the consideration!

**Comment by Fishrock123** [comment]
It would be very nice if `ds` did not run on-install scripts by default.

**Comment by chrisdickinson** [comment]
I really like run-scripts as an application-level convenience – indeed we use them all over the place in this project. I do not want to support them on installation.

I think my goal would be to provide run-scripts that work something like the following:

- Arbitrary run-scripts are okay. `ds run reticulate-splines` is a-okay.
- Nested `pre-` and `post-` hooks are great for, e.g., wiring lint to `posttest`. So, `ds run test` should run `ds run posttest`, and that should run `ds postposttest`, and so on.
- Some run-scripts should be promoted to commands: `ds test`, `ds lint`. (`ds build` already exists and has a different meaning.)
- I would like the ability to select an `env_file` for run commands.
- TOML's multiline literals make writing more complex scripts more feasible, but I'm not particularly tied to `$SHELL`. It might be nice to support JS to start, and then add `shell` later.

That is to say, you'd end up with something that looks like:

```toml
name = "chris@registry.neversaw.us/ds"
version = "1.0.0"

run.lint.shell = "eslint ."
run.test.shell = "mocha -R spec"
run.pretest.shell = "ds run lint"

[run.postbuild]
# the application is in charge of compiling submodules if it needs to.
shell = """
  for path in $(find -name "binding.gyp" node_modules); do
    cd $(dirname path); npx node-gyp .; cd -
  done
"""

[run.build]
js = """
   gulp = require("gulp")
"""
env_file = "./.env"
```

**Comment by zacanger** [comment]
Rather than `shell` and `js` in your example, if you used `bash` and `node` that would be not too scary to implement, at least on Unix-y platforms. `/usr/bin/env ${key} ${value}`

**Comment by ceejbot** [comment]
Avoiding install scripts seems like a good direction, and I think that's the consensus here. TOML is really opening up some possibilities here.

**Comment by nschonni** [comment]
Install scripts are usually needed for native Node modules in order to pull or compile bindings

**Comment by viktor-ku** [comment]
@chrisdickinson 

```toml
name = "chris@registry.neversaw.us/ds"
version = "1.0.0"

run.lint.shell = "eslint ."
run.test.shell = "mocha -R spec"
run.pretest.shell = "ds run lint"

[run.postbuild]
# the application is in charge of compiling submodules if it needs to.
shell = """
  for path in $(find -name "binding.gyp" node_modules); do
    cd $(dirname path); npx node-gyp .; cd -
  done
"""

[run.build]
js = """
   gulp = require("gulp")
"""
env_file = "./.env"
```

I believe with this approach your `package.toml` will get very big/unreadable very fast. I think that every project will find its way around writing tasks with whatever is suitable for them. `Makefile`, `bash`, `js` even `c` or `rust`. Every project has its own requirements. At the end of the day it's just an executable file that `ds` can run with some arguments.

```toml
[scripts]
test = "jest whatever"
lint = "eslint --cache ."
some-script = "ds run test & ds run lint"
my-exec = "./exec && shutdown now"
```

### Just like in NPM, huh?

Yeah, just like in npm. It's super convenient. No need to evaluate strings inside `package.toml` and run them. Let's keep it simple?

### What I personally think about life-hooks

As @nschonni pointed out `ds` probably needs to have install hooks for everything to work properly. 

But other than that life hooks are not needed at all. You can use scripts composition to do everything you really need. For example if you want to have `prebuild` "hook", you'd do

```toml
[scripts]
test = "jest ."
lint = "eslint ."
prebuild = "ds run lint & ds run test"
build = "ds run prebuild && webpack ."
```

### Commands VS scripts battle is unneeded as well

Commands are just commonly used scripts. Without life-hooks commands are useless. Every project & every developer may have it's own understanding of "build", "lint", "test", "run" process. Every repository and registry may work differently. 

Pros

- No need to learn what is running with `run` and what is running without `run`. If everything is a script, then it runs with `run`.
- Every registry can specify it's own script requirements for the projects. `build`, `build-all`, `pre-build`, `prepare`, `pretest` or even `gitlab-run` and `heroku-run` - client will specify these scripts needed *specifically* for the registry, repository, ci etc.
