### ISSUE TITLE
ds build puts modiules into 'ds' subfolder

### ISSUE THREAD

**Issue by fetis** [entropic-dev/entropic#254]
# Is this a feature request or a bug?
it seems bug for me

# Expected behavior:
put packages into `node_modules`

# Actual behavior:
packages are in `ds/node_modules`

# Steps to replicate:
so, I have fresh master and I did `npm link` in `cli` folder to install `ds` globally.

I have next Package.toml
```toml
name = "fetis@entropic.dev/test"
version = "0.0.0-beta"

[dependencies]
"legacy@registry.entropic.dev/figgy-pudding" = "^3.5.1"
```

I run `ds build`. The package is installed but into `ds` subfolder

So node module resolution is broken `const figgy = require('figgy-pudding');`

# Environment info (where relevant)

- Version of Node (`node -v`): v12.3.1
- Version of ds (`ds --version`): master ca58c5e9e4a94873577e7ce2ee7745d4d540f867

Is it expected behavior or a bug?

P.S. I tried the same with an older version from `install.sh` script -- same result.
